version: '3.8'
services:
  backend:
    build: .
    environment:
      - MONGO_URI=mongodb+srv://suzan:0000@cluster0.4bp01.mongodb.net/
      - JWT_SECRET=supersecretkey
    ports:
      - "3000:3000"
